include:
  - project: 'f1x1t/gitlab-ci'
    ref: master
    file: 'scheduled.yml'

smolensk15-nightly:
#    CMAKE_GENERATOR: Unix Makefiles
  extends: .scheduled-smolensk15

orel212-nightly:
  extends: .scheduled-orel212

bionic-nightly:
  extends: .scheduled-bionic

focal-nightly:
  extends: .scheduled-focal

elbrus-nightly:
  extends: .scheduled-elbrus

check-format-sources:
  only:
    - merge_requests
  extends: .check-format-sources
